### ISSUE TITLE
Large file support

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/av-scanner-service#6]
Currently there are some defaults set in the AV scanner for how large a file can be processed.
We need this changed to support files up to 500 MB.

**Comment by cwdcwd** [comment]
it looks like Clam AV has a `CLAMAV_MAX_FILE_SIZE` parameter that can be set

**Comment by callmekatootie** [comment]
Still trying to figure this out - the only results I have come across are using the flag mentioned above.

**Comment by callmekatootie** [comment]
I think the only way out is to add commands to the `deploy.sh` file, where we need to open terminal inside the clamav container, set the max file size and restart clamav.

**Comment by cwdcwd** [comment]
yeah I think after looking at some other images (like [this one](https://github.com/tiredofit/docker-clamav#environmentvariables) though I can't seem to make it work) we may have to create our own docker file with deploy script in it to set that value.

**Comment by cwdcwd** [comment]
[this](https://hub.docker.com/r/citizensadvice/clamav/~/dockerfile/), for instance, sets these 3 env vars that I think we should set 
```
ENV MAX_SCAN_SIZE 500M
ENV MAX_FILE_SIZE 500M
ENV MAX_STREAM_LENGTH 500M
```

**Comment by callmekatootie** [comment]
Ok. I'll explore that

**Comment by BadalZ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AV Scanner - Large file support](https://trello.com/c/xvPEc5Qq/34-av-scanner-large-file-support)

**Comment by BadalZ** [comment]
fixed this with docker image change

**Comment by callmekatootie** [comment]
I was working on the solution for this by writing the dockerfile myself. I see the solution here is to simply use another image, but are we sure about that image - it seems to no longer point to a github repository and may not be maintained...

**Comment by callmekatootie** [comment]
Sorry for the delay here though... I got stuck with my docker command not going beyond `building app`

**Comment by callmekatootie** [comment]
> Can you push the image to docker hub and share please

Note sure I understand - I thought we resolved this with the docker image change. I dropped making any further changes hence.

**Comment by BadalZ** [comment]
Docker image is placed here for reference.

https://github.com/topcoder-platform/av-scanner-service/tree/develop/clamav-docker
